import Head from 'next/head';
// import {BsFillMoonStarsFill} from "react-icons/bs";
import  {AiFillGithub, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
//import deved from "/Users/erinnclough/Desktop/portfolio/erinnclough.github.io/public";
import {useState} from 'react';


export default function Home(){
    const [darkMode, setDarkMode] = useState(false);

  return (
   <div className={darkMode ? "dark" : ""}>
    <Head>
      <title>Erin Clough Portfolio</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className= "bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
      <section classname="min-h-screen">
        <nav className="py-10 mb-12 flex justify-between dark:text-white">
          <h1 className="text-xl font-burtons"></h1>
            <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="/ErinCloughResume.pdf" target="_blank">Resume</a>
        </nav>

        <div className="text-center p-10 py-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">Erin Clough</h2>
          <h3 className="text-2xl py-2 font-medium dark:text-white md:text-3xl"></h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            
          </p>
        </div>
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400"> 
        <a target="_blank" rel="noopener noreferrer" href="https://github.com/erinnclough"><AiFillGithub /></a> 
        <a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/in/erinnclough/"><AiFillLinkedin /></a>   
        </div>
        <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
         {/* <Image src={deved} layout="fill" objectFit="cover"/> */}
        </div>
      </section>

      <section>
       {/*  <div>
          <h3 className="text-3xl py-1 dark:text-white">Services I Offer</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
          </p>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
        </div> */}

        <div className="lg:flex gap-10">
       {/*  <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className='mx-auto' src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div> */}
          {/* <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
            <Image src={design} width={100} height={100} />
            <h3 className="text-lg font-medium pt-8 pb-2 ">Beautiful Designs</h3>
            <p className="py-2">
              Creating elegant designs suiyted for your needs. 
            </p>
            <h4 className="py-4 text-teal-600">Design Tools I use</h4>
            <p className="text-gray-800 py-1">photoshop</p>
            <p className="text-gray-800 py-1">Illustrator</p>
            <p className="text-gray-800 py-1">Figma</p>
            <p className="text-gray-800 py-1">Indesign</p>
          </div> */}

         {/*  <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image className='mx-auto' src={code} width={100} height={100} />
            <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
            <p className="py-2">
              text
            </p>
            <h4 className="py-4 text-teal-600">Design Tools I use</h4>
            <p className="text-gray-800 py-1">photoshop</p>
          </div>
 */}
         {/*  <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
            <Image className='mx-auto' src={consulting} width={100} height={100}/>
            <h3 className="text-lg font-medium pt-8 pb-2">Beautiful Designs</h3>
            <p className="py-2">
              text
            </p>
            <h4 className="py-4 text-teal-600">Design Tools I use</h4>
            <p className="text-gray-800 py-1">photoshop</p>
            <p className="text-gray-800 py-1">photoshop</p>
          </div> */}
        </div>
      </section>

      <section className="py-10">
        {/* <div>
          <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
          <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                Since the beginning of my journey as a freelance designer and
                developer, I've done remote work for
                <span className="text-teal-500"> agencies </span>
                consulted for <span className="text-teal-500">startups </span>
                and collaborated with talanted people to create digital products
                for both business and consumer use.
              </p>
              <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                I offer from a wide range of services, including brand design,
                programming and teaching.
              </p>
        </div> */}

        <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap" >
         {/*  <div className="basis-1/3 flex-1">
            <Image src={web1} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web2} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web3} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" /> 
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web4} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web5} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
          </div>
          <div className="basis-1/3 flex-1">
            <Image src={web6} className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" />
          </div> */}
        </div>
      </section>

    </main>
   </div>
  );
}
